version : 1.0.0
services :
    web : 
      build : .
      ports : 
        - "8000:3000"
      depends_on : 
        - mongodb
      environment:
        - DATABASE_URI=mongodb://mongodb/docii

    redis : 
      image : redis:latest
    mongodb : 
      image : mongo
      ports:
        - 27017:27017
      environment:
        - MONGO_INITDB_ROOT_USERNAME=outofearth
        - MONGO_INITDB_ROOT_PASSWORD=Outofearth1771*


    mongo-express:
        image: mongo-express
        restart: always
        ports:
        - 8081:8081
        environment:
        - ME_CONFIG_MONGODB_SERVER=mongodb
        - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
        - ME_CONFIG_MONGODB_AUTH_DATABASE=docii
        - ME_CONFIG_MONGODB_AUTH_USERNAME=outofearth
        - ME_CONFIG_MONGODB_AUTH_PASSWORD=Outofearth1771*
        depends_on:
        - "mongodb"
